baseurl: ''
permalink: pretty
title: Jekyll Serif
logo:
  mobile: images/logo/logo-mobile.svg
  desktop: images/logo/logo.svg
  desktop_height: 36px
collections:
  services:
    output: true
  team:
    output: true
defaults:
  - scope:
      path: ''
      type: services
    values:
      layout: service
  - scope:
      path: ''
      type: team
    values:
      layout: team
sass:
  indentWidth: 4
  style: compact
  precision: 10
plugins:
  - jekyll-environment-variables
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
url: ''
